name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy-dapp-demo:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.11.1]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build:docs
      - run: cp CNAME ./dev-examples/docs/dist/
      - name: Deploy to use-wallet.fluentwallet.dev
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "use-wallet.fluentwallet.dev"
          project: "./dev-examples/docs/dist/"
          login: ${{ secrets.CONFLUX_ECO_SURGE_LOGIN}}
          token: ${{ secrets.CONFLUX_ECO_SURGE_TOKEN}}
