name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  deploy-dapp-demo:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.11.1]
    permissions:
      pages: write
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build:docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dev-examples/docs/dist